import Head from 'next/head'
import Image from 'next/image'
import { ChampionGrid } from '../components/championGrid'
import { MenuButton } from '../components/menuButton'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
            <p>swaghetti yolognese</p>
            <MenuButton></MenuButton>
            <ChampionGrid></ChampionGrid>
        </div>
      </main>
    </>
  )
}
